### ISSUE TITLE
Drow Jungling Needs to Kite

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#101]
Drow can now jungle properly with another jungler present. I implemented sharing of neutral camps if possible so bots go to different camps and not both fight the same camp (providing there is more than 1 camp they can do at their current difficulty metric).

Drow now needs to learn to kite so he doesn't sit there and take punishment.

**Comment by pbenologa** [comment]
Regarding drow i made a quick fix for that but it was really inefficient so i did not commit the changes. I changed the value 200 to bot:GetAttackRange() and it was perfect when it worked since drow will attack almost at the edge of the camp and  the creeps wil be walking towards drow with frost arrows slow. Now the problem is when finding the camps there are times the bot would report a camp as clear or empty even though there are neutral creeps inside. If there are other ways of checking if a camp is empty this would be fixed. 

> local function MoveToCamp(bot)
	if getHeroVar("currentCamp") == nil then
		JunglingState = JunglingStates.FindCamp
		return
	end
	if GetUnitToLocationDistance(bot, getHeroVar("currentCamp")[constants.VECTOR]) > 200 then

**Comment by Nostrademous** [comment]
Try:
if getHeroVar("currentCamp") == nil or camp[constants.VECTOR] ~= getHeroVar("currentCamp")[constants.VECTOR] then

**Comment by Keithenneu** [comment]
@Nostrademous That's not the issue here. A bot wont move to a camp if he knows there aren't any creeps in the first place.

There is no way for checking a camp other than having a look at it. If the distance is to big, there might something blocking the line of sight. I doubt we can calculate line of sight easily.
We need some form of kiting code. Not only for drow; bs could need some as well.

We could try to calculate a better camp approaching vector for the moment.
From the camp vector, going in the direction of the camp pre_stack_vector, by the distance equal to the attack range, should yield a vector that is as far away as you wanted it to be, while it should have a clear line of sight. Might not work for all camps though.

**Comment by pbenologa** [comment]
The current vector for neutral camps is directly on the spawn area that why bots need to go there. If only we can generate or have access vectors in front of a neutral camp this will be solved.

**Comment by Keithenneu** [comment]
I think the pre_stack_vector is somewhere between the spawn vector and the front of the camp.

**Comment by pbenologa** [comment]
Ill try this over the weekends. Since I cant do full time debugging in the office. 😂

**Comment by Nostrademous** [comment]
@Keithenneu about to push some new functions in utility.lua that will do:

1) AreTreesBetweenMeAndLoc(loc, lineOfSightThickness) - will return true if there are trees between bot's location  and specified location with a line of sight vector of specified thickness, else false. Useful for Line-Of-Sight based on tree-blocking. Useful for Timbersaw, Monkey King. Useful for setting up undetectable Mirana arrows, Pudge hooks, Clockwerk hooks, etc.

2) AreEnemyCreepsBetweenMeAndLoc(loc, lineOfSightThickness) - will return true if an enemy creep is between bot's location and specified location with a line of sight vector of specified thickness, else false.  Needed for Mirana's arrow decision making, etc.

3) U.AreFriendlyCreepsBetweenMeAndLoc(loc, lineOfSightThickness) - will return true if a friendly creep is between bot's location and specified location with a line of sight vector of specified thickness, else false. Useful as an evasive/safety check against enemy Pudge/Mirana/Clockwerk/etc

4) U.AreCreepsBetweenMeAndLoc(loc, lineOfSightThickness) - combines #2 and #3 above into one check. Useful for Pudge hook, Clockwerk Hook, etc.
