### ISSUE TITLE
Update Repository Description

### ISSUE THREAD

**Issue by PaulMaederer** [Nostrademous/Dota2-FullOverwrite#147]
The description seems kind of outdated, you may want to update it to be up2date.

**Comment by Nostrademous** [comment]
Yes I need to, but time is precious and I can either use it to update descriptions, comment code, do quality-of-life improvements or write fixes & enhancements to bot program. 

Since there are only a few contributors thus far I'm focusing on pushing the bot program with my available time so I can reach a "version 1.0 beta" in my eyes and push it to the Workshop.
