### ISSUE TITLE
Test (& Fix) Running on Dire Side

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#148]
I "tried" to make sure all code I wrote was side-agnostic, but I have not tested this. Need to see if we run correctly on the Dire side and fix what doesn't work.

This primarily is about warding locations, lane swapping, movement.. obviously skill use, item use, leveling etc. are independent of what side you are on.

**Comment by ByBurton** [comment]
Well, not regarding the dire side, but regarding testing.
I found some stuff out, or maybe you knew that already:
1. Ranged creeps are focused, and the bots keep focusing them, and even risking to die.
2. Offlane Viper is far too aggressive, the same is Drow Ranger in safelane. Mostly because they attack the ranged creep. I would really love to see some more defensive bots here, especially offlane viper, standing only in exp range (as long as he is against more then 1 other bot).
3. Lina does pretty good, did not focus on her.
4. Drow Ranger walks back if nearly out of mana, why? 
5. Drow Ranger spams her gust. uses it as soon as it is available on the offlane axe, without doing anything... -> out of mana after 20 secs.
6."Suck it", really? :D especially because they spam it...
7. I like your bots.

**Comment by pbenologa** [comment]
The ranged creep is being attacked because is has the lowest HP and when in laning the bot gets the "weakest creep" by health value. Drow Ranger gust spam was fixed on my last commit but the change i made was removed after another commit.

**Comment by Nostrademous** [comment]
Fixed initial rune spawn pickup on Dire. Works otherwise.
